version: 2.1
commands:
  test:
    steps:
      - run:
          name: test
          command: |
            pip3 install -r requirements.txt
            make test
jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - test

workflows:
  build:
    jobs:
      - build
